[build]
  command = "yarn && yarn build"
  functions = "functions"

[functions]
  directory = "api/"
  included_files = ["api/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200
  force = true
